use_frameworks!

platform :ios, '10.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
#source 'https://cdn.cocoapods.org/'
# 清华镜像
#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
#source 'https://gitee.com/mirrors/CocoaPods-Specs.git'

# axing 库
def axinger_pods
  
  # pod 'AXiOSKit' , :git => 'https://github.com/axinger/AXiOSKit.git', :branch => 'release/20190530_new'
  # pod 'AXiOSKit', :source => 'https://github.com/axinger/AXiOSKit.git'
  # pod 'AXiOSKit', source: 'https://github.com/axinger/AXiOSKit.git'
  pod 'AXiOSKit', :path => '../'
#  pod 'AXViewControllerTransitioning',:git => 'https://gitee.com/axinger/AXViewControllerTransitioning.git'
  pod 'AXViewControllerTransitioning','~>1.1.2'
#  pod 'AXCollectionObserve',:git => 'https://github.com/axinger/AXCollectionObserve.git'
  pod 'AXCollectionObserve','~>1.1.0'
end

# 因为有的target 不支持UIKit的库
def ui_pods
  
  pod 'IQKeyboardManager'
  pod 'TZImagePickerController','~>3.5.8'
  #蘑菇街团队提供了MGJRouter路由库
  pod 'MGJRouter'
  #https://github.com/casatwy/CTMediator
  #  pod 'CTMediators'
  
  #  CocoaAsyncSocket 是适用于 Mac 和 iOS 的异步套接字网络库，支持 tcp 和 udp。其中：
  #AsyncSocket 类是支持TCP的
  #AsyncUdpSocket 是支持UDP的
  #AsyncSocket 是封装了 CFSocket 和 CFSteam 的 TCP/IP socket 网络库。它提供了异步操作，本地 cocoa 类的基于delegate的完整支持。
  pod 'CocoaAsyncSocket','~>7.6.5'
  
  #  pod 'FLAnimatedImage'
  #  pod 'SocketRocket'
  #pod 'ZLPhotoBrowser'
  
  pod 'SocketRocket'
  # 安全集合
  pod 'AvoidCrash'
  # 保护App
  pod 'JJException'
  
  #  pod 'libwebp', :git => 'https://gitee.com/mirrors/libwebp.git'
  # 微信开源数据库操作层 ORM
  #  pod 'WCDB','~> 1.0.7.5'
  pod 'WCDB' , :git => 'https://gitee.com/mirrors/wcdb.git' #,:tag => '~> 1.0.8.2'
  # 微信分享,此版本才不会校验链接
  #    pod 'WechatOpenSDK','= 1.7.7'
  
  pod 'SSKeychain'
  
  # 代替 NSUserDefaults
  pod 'MMKV','~>1.2.7'
  
  #  pod 'MJRefresh'
  #  pod 'NullSafe'
  #  pod 'MJExtension'
  #  pod 'MBProgressHUD'
  #  pod 'DZNEmptyDataSet'
  #  #pod 'SDCycleScrollView'
  #  pod 'KVOController'
  #  pod 'Masonry'
  #  #pod 'GKPhotoBrowser'
  #  pod 'Aspects'
  pod 'MGSwipeTableCell','~> 1.6.11'
  
  pod 'Canvas', '~> 0.1.2'
  pod 'RMQClient'
  pod 'MQTTClient'
  pod 'MQTTClient/Websocket'
  pod 'Bagel', '~>  1.4.0'
  
  #OOMDetector是一个iOS内存监控组件，应用此组件可以帮助你轻松实现OOM监控、大内存分配监控、内存泄漏检测等功能。
  #  pod 'OOMDetector', '1.3'
  # hook c函数
  pod 'fishhook'
  
  # GDataXML 的包裹
  pod 'GDataXML-HTML', '~> 1.4.1'
  
  # Instagram在2016年年底发布了基于数据驱动的UICollectionView框架IGListKit
  #  pod 'IGListKit', '~> 4.0.0'
  pod 'IGListKit'
  #  pod 'YYKit'
  #  pod 'GRDB.swift'
  
  # 一行代码解决iOS启动图的各种疑难杂症
  pod 'LLDynamicLaunchScreen','~>0.2.0'
  # 新版本是swift
  #  pod 'lottie-ios'
  # 旧版本是oc
  pod 'lottie-ios', '~>2.5.3'
  # 图片剪切
  #  pod 'PEPhotoCropEditor'
  # 在不同的控制器中实现UINavigationBar不同地样式
  #  pod 'KMNavigationBarTransition'
  
  #  # 导航栏,可以每个VC不一样配置
  #  pod 'RTRootNavigationController',:git => 'https://gitee.com/mirrors/RTRootNavigationController.git'
  #  pod "Protobuf", :git => 'https://gitee.com/axinger/protobuf.git'
  #  pod "YYKit", :git => 'https://gitee.com/mirrors/yykit.git',:tag =>'1.0.9'
  #  pod "YYText", :git => 'https://gitee.com/mirrors/YYText.git',:tag =>'1.0.7'
  #  pod "YYCategories", :git => 'https://gitee.com/mirrors/YYCategories.git',:tag =>'1.0.4'
  #  pod 'YYKeyboardManager' , :git => 'https://gitee.com/github-iOS/YYKeyboardManager.git',:tag =>'1.0.1'
  #  pod 'YYCache' , :git => 'https://gitee.com/github-iOS/YYCache.git',:tag =>'1.0.4'
  #  pod 'YYDispatchQueuePool' , :git => 'https://gitee.com/github-iOS/YYDispatchQueuePool.git',:tag =>'1.0'
  
  # 导航栏,可以每个VC不一样配置
  pod 'RTRootNavigationController','~> 0.8.0'
  pod "Protobuf",'~> 3.15.8'
  pod "YYText",'~> 1.0.7'
  pod "YYCategories", '~> 1.0.4'
  pod 'YYKeyboardManager' ,  '~> 1.0.1'
  pod 'YYCache' , '~> 1.0.4'
  pod 'YYDispatchQueuePool' ,  '~> 1.0'
  
  # 分享
  pod 'MonkeyKing'
end


#一般小写字母、下划线开头：变量（Variable）。
#$开头：全局变量（Global variable）。
#@开头：实例变量（Instance variable）。
#@@开头：类变量（Class variable）类变量被共享在整个继承链中
#大写字母开头：常数（Constant）。


DebugList=['Debug','Debug_α','Debug_β']
# 测试工具
def debug_pods
  # LookinServer 和 Reveal-SDK 类似
  
  pod 'LLDebugTool' , '1.3.8.1' ,:configurations => DebugList
#  pod 'MLeaksFinder', '~> 1.0.0' ,:configurations => DebugList
  #  pod 'LookinServer', :configurations => ['Debug']
#  pod 'LookinServer', :configurations => DebugList, :git => 'https://gitee.com/axinger/LookinServer.git'
  pod 'CocoaDebug', '~> 1.6.3' , :configurations => DebugList
  #  pod 'Reveal-SDK', :configurations => ['Debug','Debug_α','Debug_β']
  
end



# 常用的第三方
def common_pods
  
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'ReactiveObjC','~> 3.0.0'
  pod 'PromisesObjC','~> 1.2.12'
  pod 'SDWebImageFLPlugin'
  pod 'SDWebImageWebPCoder','~> 0.8.1'
  #  pod 'SDWebImage/GIF'
  pod 'SDWebImage','~> 5.10.3'
  # 网络请求模拟库OHHTTPStubs
  pod 'OHHTTPStubs', '~> 9.1.0'
  
  # 图片剪切
  pod 'TOCropViewController', '~> 2.6.0'
  pod "CTMediator"
  
  #  pod 'SSZipArchive',:git => 'https://gitee.com/axinger/ZipArchive.git'
  pod 'SSZipArchive'
  #   pod 'CYLTabBarController' # 默认不依赖Lottie
  pod 'CYLTabBarController/Lottie'  # 依赖Lottie库
  #日志
  pod 'CocoaLumberjack'
  
  # 文件
  #  pod 'FileBrowser', '~> 1.0'
end

def app_pods
  common_pods
  ui_pods
  debug_pods
  axinger_pods
end

def extension_pods
  common_pods
  axinger_pods
end

#=========环境===========
target 'AXiOSKit_Example' do
  
  app_pods
  
end

target 'AXShare' do
  
  extension_pods
  
end

#=========环境1===========
target 'AXiOSKit_Example_Env_1' do
  
  app_pods
  
end

target 'AXShare_Env_1' do
  
  extension_pods
  
end


#=========忽略===========
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  end
end
