use_frameworks!

platform :ios, '9.0'

target 'AXiOSKit_Example' do
  pod 'AXiOSKit', :path => '../'
  
  #    pod 'AXiOSKit' , :git => 'https://github.com/AXinger/AXiOSKit.git', :branch => 'release/20190530_new'
  # pod 'AXiOSKit', :source => 'https://github.com/AXinger/AXiOSKit.git'
  #  pod "FLAnimatedImage"
  pod 'SDWebImageFLPlugin'
  pod 'SDWebImageWebPCoder'
  #  pod "SDWebImage/GIF"
  #  pod 'libwebp', :git => 'https://github.com/webmproject/libwebp.git'
  pod 'SDWebImage','~> 5.7.3'
  #  pod "SocketRocket"
  pod "TZImagePickerController"
  #pod "ZLPhotoBrowser"
  pod "PromisesObjC"
  pod "SocketRocket"
  # 安全集合
  pod 'AvoidCrash'
  # 保护App
  pod 'JJException'
  # 微信开源数据库操作层 ORM
  pod 'WCDB'
  #pod 'LookinServer', :configurations => ['Debug']
  
  pod 'SSKeychain'
  #蘑菇街团队提供了MGJRouter路由库
  pod 'MGJRouter'
  #https://github.com/casatwy/CTMediator
  #  pod 'CTMediators'
  
  #  CocoaAsyncSocket 是适用于 Mac 和 iOS 的异步套接字网络库，支持 tcp 和 udp。其中：
  #AsyncSocket 类是支持TCP的
  #AsyncUdpSocket 是支持UDP的
  #AsyncSocket 是封装了 CFSocket 和 CFSteam 的 TCP/IP socket 网络库。它提供了异步操作，本地 cocoa 类的基于delegate的完整支持。
  pod "CocoaAsyncSocket"
  
  pod "Masonry"
  pod "AFNetworking"
  pod "IQKeyboardManager"
  pod 'WechatOpenSDK','1.7.7'
  #  pod "MJRefresh"
  #  pod "NullSafe"
  #  pod "MJExtension"
  #  pod "MBProgressHUD"
  #  pod "DZNEmptyDataSet"
  #  #pod "SDCycleScrollView"
  #  pod "KVOController"
  #  pod "Masonry"
  #  #pod "GKPhotoBrowser"
  #  pod "Aspects"
  pod 'MGSwipeTableCell','~> 1.6.11'
  
  pod 'MLeaksFinder'
  pod 'ReactiveObjC'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'Canvas', '~> 0.1.2'
  
  pod 'RMQClient'
  pod 'MQTTClient'
  pod 'MQTTClient/Websocket'
  pod 'Bagel', '~>  1.3.2'
  pod 'LLDebugTool' , '~> 1.0'
  target 'AXiOSKit_Tests' do
    inherit! :search_paths
    
    
  end
end
