#!/bin/sh

if [[ $1 != "" ]]; then

    echo "======开始修改spec文件版本号======"
    sed -i "" "s/spec.version.*=.*/spec.version      = '$1' /g" AXiOSTools.podspec

    if [ $? -ne 0 ]; then
        echo "修改spec文件失败"
        exit 0
    else
        echo "修改spec文件成功，version：$1"
        git add -A && git commit -m "修改spec文件版本号:$1"
        git push origin master
    fi

    echo "======开始打tag:$1======"
    git tag $1
    #是否执行成功
    if [ $? -ne 0 ]; then
        echo "打tag失败"
        # pod repo push cnsuning-tysq-suningsportsspecs AXiOSTools.podspec --verbose --allow-warnings --sources=https://github.com/AXinger/AXiOSTools.git
    pod trunk push AXiOSTools.podspec
    else
        echo "打tag成功"
        git push --tags
        echo "======开始推送spec文件======"
        # pod repo push cnsuning-tysq-suningsportsspecs AXiOSTools.podspec --verbose --allow-warnings --sources=https://github.com/AXinger/AXiOSTools.git
    pod trunk push AXiOSTools.podspec
    fi
else
    echo "======请输入tag======"
fi
