project 'AXiOSToolsExample.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'AXiOSToolsExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AXiOSToolsExample
pod 'AXiOSTools', :path => '../'
#pod 'AXiOSTools' , :git => 'https://github.com/AXinger/AXiOSTools.git'
pod 'FLAnimatedImage'
pod 'SDWebImage/GIF'
pod 'SocketRocket'
end
