platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

#baseUrl = 'http://git.GitHub.com/ios/'
#source baseUrl+'axingspecs.git'


target 'AXiOSToolsExample' do
    project 'AXiOSToolsExample.xcodeproj'
    
    pod 'AXiOSTools', :path => '../'
    
    #pod 'AXiOSTools' , :git => 'https://github.com/AXinger/AXiOSTools.git'
    pod 'FLAnimatedImage'
    pod 'SDWebImage/GIF'
    pod 'SocketRocket'
end

#target 'AXiOSTools' do
#    project 'AXiOSTools.xcodeproj'
#
#    pod 'FLAnimatedImage'
#    pod 'SDWebImage/GIF'
#    pod 'SocketRocket'
#end


