CREATE TABLE IF NOT EXISTS t_user(
  id INTEGER PRIMARY KEY,
  name TEXT,
  age INTEGER
);
|
CREATE TABLE IF NOT EXISTS t_person (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  age INTEGER
);
