// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Dog;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - StudentRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface StudentRoot : GPBRootObject
@end

#pragma mark - Dog

typedef GPB_ENUM(Dog_FieldNumber) {
  Dog_FieldNumber_Name = 1,
  Dog_FieldNumber_Age = 2,
  Dog_FieldNumber_Gender = 3,
};

GPB_FINAL @interface Dog : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) int64_t age;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gender;

@end

#pragma mark - Student

typedef GPB_ENUM(Student_FieldNumber) {
  Student_FieldNumber_Name = 1,
  Student_FieldNumber_Age = 2,
  Student_FieldNumber_Gender = 3,
  Student_FieldNumber_DogArray = 4,
  Student_FieldNumber_Dog2 = 5,
};

GPB_FINAL @interface Student : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) int64_t age;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gender;

/** 数组 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Dog*> *dogArray;
/** The number of items in @c dogArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger dogArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) Dog *dog2;
/** Test to see if @c dog2 has been set. */
@property(nonatomic, readwrite) BOOL hasDog2;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
