install! 'cocoapods', :warn_for_multiple_pod_sources => false
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

#baseUrl = 'http://git.GitHub.com/ios/'
#source baseUrl+'axingspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'AXiOSKitExample.xcworkspace'

# demo 依赖
target 'AXiOSKitExample' do
  project 'AXiOSKitExample.xcodeproj'
  
    pod 'AXiOSKit', :path => '../'
  #    pod 'AXiOSKit' , :git => 'https://github.com/AXinger/AXiOSKit.git', :branch => 'release/20190530_new'
  # pod 'AXiOSKit', :source => 'https://github.com/AXinger/AXiOSKit.git'
  #  pod "FLAnimatedImage"
  pod 'SDWebImageFLPlugin'
  pod 'SDWebImageWebPCoder'
  #  pod "SDWebImage/GIF"
  #  pod 'libwebp', :git => 'https://github.com/webmproject/libwebp.git'
  pod 'SDWebImage','~> 5.7.3'
  #  pod "SocketRocket"
  pod "TZImagePickerController"
  #pod "ZLPhotoBrowser"
  pod "PromisesObjC"
  pod "SocketRocket"
  # 安全集合
  pod 'AvoidCrash'
  # 保护App
  pod 'JJException'
  # 微信开源数据库操作层 ORM
  pod 'WCDB'
  #pod 'LookinServer', :configurations => ['Debug']
  
  pod 'SSKeychain'
  #蘑菇街团队提供了MGJRouter路由库
  pod 'MGJRouter'
  #https://github.com/casatwy/CTMediator
#  pod 'CTMediators'
  
  pod "Masonry"
  pod "AFNetworking"
  pod "IQKeyboardManager"
  pod 'WechatOpenSDK','1.7.7'
#  pod "MJRefresh"
#  pod "NullSafe"
#  pod "MJExtension"
#  pod "MBProgressHUD"
#  pod "DZNEmptyDataSet"
#  #pod "SDCycleScrollView"
#  pod "KVOController"
#  pod "Masonry"
#  #pod "GKPhotoBrowser"
#  pod "Aspects"
end

#AXiOSKit 依赖
target 'AXiOSKit' do
  project '../AXiOSKit.xcodeproj'

  pod "AFNetworking"

  pod "IQKeyboardManager"
  pod "MJRefresh"
  pod "NullSafe"
  pod "MJExtension"
  pod "MBProgressHUD"
  pod "DZNEmptyDataSet"
  #pod "SDCycleScrollView"
  pod "KVOController"
  pod "Masonry"
  #pod "GKPhotoBrowser"
  pod "Aspects"

end


