install! 'cocoapods', :warn_for_multiple_pod_sources => false
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

#baseUrl = 'http://git.GitHub.com/ios/'
#source baseUrl+'axingspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'AXiOSKitExample.xcworkspace'

target 'AXiOSKitExample' do
  project 'AXiOSKitExample.xcodeproj'
  
  pod 'AXiOSKit', :path => '../'
  #    pod 'AXiOSKit' , :git => 'https://github.com/AXinger/AXiOSKit.git', :branch => 'release/20190530_new'
  
  pod "FLAnimatedImage"
  pod "SDWebImage/GIF"
#  pod "SocketRocket"
  pod "TZImagePickerController"
  pod "ZLPhotoBrowser"
  pod "PromisesObjC"
  
  
  pod "SocketRocket"
  
  ## 安全集合
  pod 'AvoidCrash'

  ## 保护App
  pod 'JJException'
  
  # 微信开源数据库操作层
  pod 'WCDB'
  
end

target 'AXiOSKit' do
  project '../AXiOSKit.xcodeproj'
  
  pod "AFNetworking"
  pod "SDWebImage"
  pod "IQKeyboardManager"
  pod "MJRefresh"
  pod "NullSafe"
  pod "MJExtension"
  pod "MBProgressHUD"
  pod "DZNEmptyDataSet"
  pod "SDCycleScrollView"
  pod "KVOController"
  pod "Masonry"
  #pod "GKPhotoBrowser"
  pod "Aspects"
  pod "TZImagePickerController"
  
  pod "ZLPhotoBrowser"
  pod 'LookinServer', :configurations => ['Debug']
  
end


